"""
Encryption for member Walden logins at rest (issues #179 and #242).

Two schemes, told apart by a prefix on the stored value:

* ``kms1:`` - Cloud KMS (#242), what new logins are written with once
  CREDENTIAL_KMS_KEY is set. The key material lives in KMS and cannot be
  exported by anyone, and with Data Access audit logs on (terraform/kms.tf)
  every decrypt is recorded with the identity that made it. Nobody holds a copy
  of the key, so reading a member's password means a call that leaves a trace.
* No prefix - Fernet with CREDENTIAL_ENCRYPTION_KEY (#179). That key was
  generated by hand and copied to the maintainer's machine, so anyone holding
  it could decrypt every row with no record. Still read, so existing logins
  keep working until their members re-enter them; written only when no KMS key
  is configured (local development).

Each KMS ciphertext is bound to its row and field with additional
authenticated data (``walden_credentials:<requester>:<field>``). A ciphertext
copied onto another member's row, or from the login column into the password
column, fails to decrypt instead of quietly booking under the wrong login.

KMS is a network call, which #179 avoided because credential resolution sits on
the path to every booking. It sits before the race, not in it: the racer
resolves a login at 06:28, when it logs in, two minutes before the window.

Calls go to the KMS REST API with httpx and google-auth's application default
credentials, the same pattern as the observer's GCS uploads
(app/observer/artifacts.py), so this adds no dependency.
"""

import asyncio
import base64
import logging
import time

import google.auth
import httpx
from cryptography.fernet import Fernet, InvalidToken
from google.auth.transport.requests import Request as GoogleAuthRequest

from app.config import settings

logger = logging.getLogger(__name__)

KMS_PREFIX = "kms1:"
KMS_API = "https://cloudkms.googleapis.com/v1"
_KMS_SCOPES = ["https://www.googleapis.com/auth/cloudkms"]
_KMS_TIMEOUT_S = 10.0

# Application default credentials, refreshed when they expire. One instance per
# process; google-auth's refresh is cheap when the token is still valid.
_credentials: google.auth.credentials.Credentials | None = None
# Tests point this at an httpx.MockTransport standing in for KMS.
_transport: httpx.AsyncBaseTransport | None = None


class CredentialEncryptionError(RuntimeError):
    """Raised when a member's credential can't be encrypted or decrypted."""


def scheme_of(stored: str) -> str:
    """Which scheme a stored value was written with: "kms" or "fernet".

    Reads only the prefix, so it needs no key. Used to confirm, before the
    Fernet key is deleted, that no row still depends on it.
    """
    return "kms" if stored.startswith(KMS_PREFIX) else "fernet"


def _aad(context: str) -> str:
    return base64.b64encode(f"walden_credentials:{context}".encode()).decode()


async def encrypt(value: str, *, context: str) -> str:
    """Encrypt a credential field for storage.

    ``context`` names the row and field (e.g. "<requester>:password") and is
    bound into a KMS ciphertext, so the same context is needed to decrypt it.
    The Fernet scheme ignores it.
    """
    key = settings.credential_kms_key.strip()
    if key:
        body = {
            "plaintext": base64.b64encode(value.encode()).decode(),
            "additionalAuthenticatedData": _aad(context),
        }
        response = await _kms_call(f"{key}:encrypt", body)
        ciphertext = response.get("ciphertext")
        if not isinstance(ciphertext, str) or not ciphertext:
            raise CredentialEncryptionError("KMS encrypt returned no ciphertext")
        return f"{KMS_PREFIX}{ciphertext}"
    return _fernet().encrypt(value.encode()).decode()


async def decrypt(stored: str, *, context: str) -> str:
    """Decrypt a credential field read from storage, whichever scheme wrote it."""
    if not stored.startswith(KMS_PREFIX):
        try:
            return _fernet().decrypt(stored.encode()).decode()
        except InvalidToken as e:
            raise CredentialEncryptionError(
                "Stored credential could not be decrypted - CREDENTIAL_ENCRYPTION_KEY "
                "may have changed since it was written."
            ) from e

    key = settings.credential_kms_key.strip()
    if not key:
        raise CredentialEncryptionError(
            "This credential was encrypted with Cloud KMS, but CREDENTIAL_KMS_KEY is not "
            "configured (credential_kms_enabled in terraform)."
        )
    body = {
        "ciphertext": stored.removeprefix(KMS_PREFIX),
        "additionalAuthenticatedData": _aad(context),
    }
    response = await _kms_call(f"{key}:decrypt", body)
    plaintext = response.get("plaintext")
    if not isinstance(plaintext, str):
        raise CredentialEncryptionError("KMS decrypt returned no plaintext")
    return base64.b64decode(plaintext).decode()


def _fernet() -> Fernet:
    """Build a Fernet cipher from CREDENTIAL_ENCRYPTION_KEY, or raise."""
    if not settings.credential_encryption_key:
        raise CredentialEncryptionError(
            "CREDENTIAL_ENCRYPTION_KEY is not configured, and neither is CREDENTIAL_KMS_KEY; "
            "cannot read or write member Walden logins."
        )
    try:
        return Fernet(settings.credential_encryption_key.encode())
    except (ValueError, TypeError) as e:
        raise CredentialEncryptionError(f"CREDENTIAL_ENCRYPTION_KEY is invalid: {e}") from e


def _access_token() -> str:
    """A current OAuth token for KMS, from application default credentials. Blocking."""
    global _credentials
    if _credentials is None:
        _credentials, _ = google.auth.default(scopes=_KMS_SCOPES)  # type: ignore[no-untyped-call]
    if not _credentials.valid:
        _credentials.refresh(GoogleAuthRequest())  # type: ignore[no-untyped-call]
    token = _credentials.token
    if not token:
        raise CredentialEncryptionError("Could not obtain a token for Cloud KMS")
    return str(token)


async def _kms_call(path: str, body: dict[str, str]) -> dict[str, object]:
    """POST to the KMS REST API. Never logs or raises with the request body."""
    started = time.perf_counter()
    try:
        token = await asyncio.to_thread(_access_token)
    except google.auth.exceptions.GoogleAuthError as e:
        raise CredentialEncryptionError(
            f"Cloud KMS credentials unavailable: {type(e).__name__}"
        ) from None
    try:
        async with httpx.AsyncClient(timeout=_KMS_TIMEOUT_S, transport=_transport) as client:
            resp = await client.post(
                f"{KMS_API}/{path}", json=body, headers={"Authorization": f"Bearer {token}"}
            )
    except httpx.HTTPError as e:
        raise CredentialEncryptionError(f"Cloud KMS unreachable: {type(e).__name__}") from None
    if resp.status_code != 200:
        # Status only. A KMS error body describes the request, and the request
        # carries the plaintext or the ciphertext.
        raise CredentialEncryptionError(f"Cloud KMS answered HTTP {resp.status_code}")
    try:
        result = resp.json()
    except ValueError:
        raise CredentialEncryptionError(
            "Cloud KMS answered with something other than JSON"
        ) from None
    if not isinstance(result, dict):
        raise CredentialEncryptionError("Cloud KMS answered with an unexpected shape")
    operation = path.rsplit(":", 1)[-1]
    logger.debug(f"Cloud KMS {operation} took {(time.perf_counter() - started) * 1000:.0f}ms")
    return result
