###############################################################################
# Member Walden logins encrypted with a Cloud KMS key (issue #242)
#
# Before this, logins were encrypted with CREDENTIAL_ENCRYPTION_KEY, a Fernet
# key the maintainer generated by hand and kept a copy of: anyone holding it and
# a database read could decrypt every row, and nothing recorded that they had.
# KMS key material cannot be exported by anyone, and with Data Access audit logs
# on, every decrypt is logged with the identity that made it.
#
# The honest limit: the service has to decrypt a login to use it, and the
# project's Owners (the maintainer, and teetime-build, which holds roles/owner)
# can grant themselves decrypt. The guarantee is not "impossible" - it is
# "nobody holds the key, and any look is recorded". The maintainer accepted the
# audit log as the safeguard on 2026-10-02.
#
# The key and its grants are created unconditionally - they are inert until
# used. credential_kms_enabled decides whether the app is told about the key,
# and so whether new logins are written with it. See variables.tf.
###############################################################################

resource "google_kms_key_ring" "credentials" {
  name     = "${local.service_name}-credentials"
  location = var.region

  depends_on = [google_project_service.apis]
}

resource "google_kms_crypto_key" "walden_logins" {
  name     = "walden-logins"
  key_ring = google_kms_key_ring.credentials.id
  purpose  = "ENCRYPT_DECRYPT"

  # A new primary version every 90 days. Old versions stay enabled, so rows
  # encrypted under them keep decrypting; KMS records which version wrote each
  # ciphertext.
  rotation_period = "7776000s"

  lifecycle {
    # Destroying this key makes every stored login unreadable, with no
    # recovery. A change that would replace it must fail the apply instead.
    prevent_destroy = true
  }
}

# The service writes logins (the setup form, #240) and reads them; the racer
# runs as the same account and reads them at login.
resource "google_kms_crypto_key_iam_member" "cloud_run_encrypt_decrypt" {
  crypto_key_id = google_kms_crypto_key.walden_logins.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = "serviceAccount:${google_service_account.cloud_run.email}"
}

# The observer only ever reads the login of the booking it watches.
resource "google_kms_crypto_key_iam_member" "observer_decrypt" {
  crypto_key_id = google_kms_crypto_key.walden_logins.id
  role          = "roles/cloudkms.cryptoKeyDecrypter"
  member        = "serviceAccount:${google_service_account.observer.email}"
}

# Record every use of a KMS key with the identity behind it. Decrypt and
# encrypt are DATA_READ/DATA_WRITE operations, which Cloud Audit Logs does not
# keep unless asked. This is the safeguard: a person reading a member's login
# leaves an entry that names them. Read them with the query in
# operations/credential-encryption.md ("Who has read a login").
resource "google_project_iam_audit_config" "kms" {
  project = var.project_id
  service = "cloudkms.googleapis.com"

  audit_log_config {
    log_type = "DATA_READ"
  }
  audit_log_config {
    log_type = "DATA_WRITE"
  }
}
